//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikaroon.ScriptTemplater {
    using UnityEditor;
    
    
    public class ScriptTemplaterMenuHook {
        
        [MenuItem("Assets/Create/Create SampleMonoBehaviour", true, 81)]
        private static bool SampleMonoBehaviourValidate() {
            return ScriptBuilder.ValidateSelection();
        }
        
        [MenuItem("Assets/Create/Create SampleMonoBehaviour", false, 81)]
        private static void SampleMonoBehaviour() {
            ScriptBuilder.GenerateFile(0);
        }
    }
}
