//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikaroon.CSTT {
    using UnityEditor;
    
    
    public class CSTTMenuHook {
        
        [MenuItem("Assets/Create/Create ExampleTemplate", true, 81)]
        private static bool ExampleTemplateValidate() {
            return ScriptBuilder.ValidateSelection();
        }
        
        [MenuItem("Assets/Create/Create ExampleTemplate", false, 81)]
        private static void ExampleTemplate() {
            ScriptBuilder.GenerateFile("ExampleTemplate", @"// <copyright file=""#FILE#"" company=""#COMPANY#"">
// Copyright (c) #YEAR# All Rights Reserved
// </copyright>
// <author>#UNITYUSER#</author>
// <date>#DATE#</date>
// <summary>A class created a custom template!</summary>

using UnityEngine;

namespace #FOLDER#
{
	public class #NAME#
	{
	}
}");
        }
    }
}
