//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikaroon.CSTT {
    using UnityEditor;
    
    
    public class CSTTMenuHook {
        
        [MenuItem("Assets/Create/Create Example Template", true, 81)]
        private static bool ExampleTemplateValidate() {
            return ScriptBuilder.ValidateSelection();
        }
        
        [MenuItem("Assets/Create/Create Example Template", false, 81)]
        private static void ExampleTemplate() {
            ScriptBuilder.GenerateFile(0);
        }
    }
}
